//===-- APSOps.td - Entry point for APS dialect bindings ---*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_APS_OPS
#define PYTHON_BINDINGS_APS_OPS

include "APS/APSOps.td"

#endif
